### ISSUE TITLE
Button binnen een <a>

### ISSUE THREAD

**Issue by lemuelmgsn** [Ronabundy1/connect-your-tribe-profile-card#1]
https://github.com/Ronabundy1/connect-your-tribe-profile-card/blob/32ee55cbddf19f0abaa86b5fb684afc5d2a58e02/views/index.ejs#L12-L23

Je button element zit binnen een a element wat niet mag.

Oplossing:
Je zou de button weg kunnen halen en de styling toepassen op de `<a>`

Bron: https://www.reddit.com/r/webdev/comments/ce4w59/is_it_bad_practice_to_wrap_a_button_in_an_a_href/?rdt=58648

**Comment by Ronabundy1** [comment]
ty
