### ISSUE TITLE
Button element binnen een a is niet mogelijk

### ISSUE THREAD

**Issue by DamianR2004** [Ronabundy1/connect-your-tribe-profile-card#4]
Kleine tip. Want je mag geen gebruik maken van een button binnen een a element. 

https://github.com/Ronabundy1/connect-your-tribe-profile-card/blob/32ee55cbddf19f0abaa86b5fb684afc5d2a58e02/views/index.ejs#L16-L18

Je kan deze bron nog eventueel doornemen! 

https://rocketvalidator.com/html-validation/the-element-button-must-not-appear-as-a-descendant-of-the-a-element

**Comment by Ronabundy1** [comment]
wist ik nog niet, bedankt
