### ISSUE TITLE
Je lijkt een button binnen een a element te gebruiken.

### ISSUE THREAD

**Issue by Patrickkhr** [Ronabundy1/connect-your-tribe-profile-card#6]
https://github.com/Ronabundy1/connect-your-tribe-profile-card/blob/32ee55cbddf19f0abaa86b5fb684afc5d2a58e02/views/index.ejs#L13-L21

Je gebruikt een button binnen de a maar dat is niet mogelijk

Je kan het button element weghalen en de styling op het a element zetten

Hier kan je meer informatie over het a element vinden: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

**Comment by Ronabundy1** [comment]
thanks voor de feedback
