### ISSUE TITLE
Div gebruik

### ISSUE THREAD

**Issue by lisavanmansom** [Ronabundy1/connect-your-tribe-profile-card#7]
Je maakt gebruik van veel divs, om de html semantischer te maken kan je ook articles of sections gebruiken. In het voorbeeld hieronder had je bijvoorbeeld een section kunnen gebruiken.

https://github.com/Ronabundy1/connect-your-tribe-profile-card/blob/32ee55cbddf19f0abaa86b5fb684afc5d2a58e02/views/index.ejs#L4

bronnen:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

**Comment by Ronabundy1** [comment]
dankje wel voor de feedback, sections heb ik ook nu toegepast in mijn html
