### ISSUE TITLE
Inspringen HTML

### ISSUE THREAD

**Issue by Akikosophia** [Ronabundy1/connect-your-tribe-profile-card#8]
Je kunt wat spaties tussen de regels houden zodat het er wat cleaner uit ziet! :) 

https://github.com/Ronabundy1/connect-your-tribe-profile-card/blob/32ee55cbddf19f0abaa86b5fb684afc5d2a58e02/views/index.ejs#L8-L23

**Comment by Ronabundy1** [comment]
dankje wel heb ik opgelost!
